### ISSUE TITLE
Possible Corpy Load Issue

### ISSUE THREAD

**Issue by RogerHuba** [TW2002/mombot#26]
Got this on bot load.

Type sub-space message [<ENTER> to send line. Blank line to end transmission]
S: [General] {hunt} -
S:  Logging corp mates automatically - and Siymonand Siymon are
S:  added.

This was the corpy list

    Corp Member Name                   Sector  Fighters Shields Mines  Credits
------------------------------------------------------------------------------
The Bounty Hunter                      13761P   50000    9715     0          0
Siymon                                          13761     2500         0       0      75T
P indicates Trader is on a planet in that sector

**Comment by stevenruzicka** [comment]
Potential fix pushed up - I don't have time to test it, but I believe the issue was the logic was checking for corpy list being equal to 1 meaning you only have one corpy.  However, it counts yourself as well.  So I changed the logic to be when the corpy size is equal to 2.  Then it adds the and between names.  Simply a formatting issue, not a functional one.  Just me trying to be fancy I guess heh.  But if someone could test it, I'd appreciate it.

**Comment by RogerHuba** [comment]
Tested and fixed. Closing issue.
